MBunPacked/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hand Cash</fullName>
                </value>
                <value>
                    <fullName>Online Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Show_Time__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Show Time</label>
        <referenceTo>Show_Time__c</referenceTo>
        <relationshipLabel>Book Show</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MBunPacked/objects/Movie__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Director__c</fullName>
        <label>Director</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Thumbnail__c</fullName>
        <label>Thumbnail</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <label>Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>9:00 AM - 11:30 AM</fullName>
                </value>
                <value>
                    <fullName>12:00 PM - 2:30 PM</fullName>
                </value>
                <value>
                    <fullName>3:00 PM - 5:30 PM</fullName>
                </value>
                <value>
                    <fullName>6:00 PM - 8:30 PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MBunPacked/objects/Show_Time__c.object
<CustomObject>
    <fields>
        <fullName>Movie__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Movie</label>
        <referenceTo>Movie__c</referenceTo>
        <relationshipLabel>Show Times</relationshipLabel>
        <relationshipName>Show_Times</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show_Time__c</fullName>
        <label>Show Time</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <label>Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Morning</fullName>
                </value>
                <value>
                    <fullName>Afternoon</fullName>
                </value>
                <value>
                    <fullName>Evening</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Show Time</label>
    <nameField>
        <label>Show Time Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Show Times</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/main/default/classes/MB_Movie_Controller.cls
/**
* Apex controller for MB Aura and LWC Components
*/ 
public with sharing class MB_Movie_Controller {
    
    @AuraEnabled
    public static list<Movie__c> getThumbnail(String movieId){
        Id movId = (Id) movieId;
        List<Movie__c> movie = [SELECT Id,Thumbnail__c FROM Movie__c WHERE Id =: movId];
        return movie;
        
        
    }
    @AuraEnabled
    public static List<Booking__c> getBookingThumbnail(String bookingId){
        Id bookId = (Id) bookingId;
        List<Booking__c> book = [SELECT Id,Show_Time__r.Movie__r.Thumbnail__c FROM Booking__c WHERE Id =: bookId];
        return book;
        
        
    }
    
    
    @AuraEnabled
    public static list<Movie__c> getMoviesDetail(String movId){
        Id MovieId = (Id) movId;
        list<Movie__c> movie = [SELECT Id, Name, Description__c, Director__c, Length__c, Thumbnail__c FROM Movie__c WHERE Id =: MovieId];
        return movie;
    }
    @AuraEnabled
    public static list<Movie__c> getAllMovies(){
        return [SELECT Id, Name, Description__c, Director__c, Length__c, Thumbnail__c FROM Movie__c];
    }
    @AuraEnabled
    public static list<Booking__c> getBooking(){
        return [SELECT Id, Name,Email__c,Payment__c  FROM Booking__c];
    }
    
    @AuraEnabled
    public static list<Show_Time__c> getMoviesBasedOnShowTime(String showTime){
        return [SELECT Id,Movie__c,Movie__r.Name,Movie__r.Thumbnail__c,Movie__r.Length__c,Movie__r.Director__c,Movie__r.Description__c FROM Show_Time__c WHERE Time__c  =: showTime AND Show_Time__c =: Date.Today()];
    }
    
    @AuraEnabled
    public static list<Show_Time__c> getTodayShow(){        
        return [SELECT Id,Name,Show_Time__c,Time__c,Movie__r.Name,Movie__r.Thumbnail__c FROM Show_Time__c WHERE Show_Time__c = today];
        
    }
    @AuraEnabled
    public static list<Show_Time__c> getTomorrowShow(){
     
        return [SELECT Id,Name,Show_Time__c,Time__c,Movie__r.Name,Movie__r.Thumbnail__c FROM Show_Time__c WHERE Show_Time__c = Tomorrow];
        
    }
    
    @AuraEnabled
    public static Boolean mbSaveRecords(String movieDetails){
        return false;
    }
    
}